# shellcheck shell=bash
# devlab-setup-lib.sh — the ONE source of a service's first-time SETUP product and the rules that
# guard it. It is SOURCED (never executed), defines only functions plus one constant, and touches no
# global state, so three consumers can share it without a second copy of any template or rule:
#
#   1. devlab-install (dev)      — GENERATES unit/route/account directly INTO this host at first-time
#                                   setup, from these templates with validated values.
#   2. devlab-exec artifact-build/emit-setup (dev, as the runner) — EMITS exactly the same product into
#                                   the delivery artifact (<artifact>/setup/…), so the bytes that reach
#                                   production are the bytes this one template produces.
#   3. devlab-deploy-recv (prod) — INSTALLS the delivered product on the production host when the unit
#                                   is missing, guarded by the SAME name/namespace/identity rules.
#
# "Ein Erzeuger, ein Installierer; die Vorlage bleibt an einer Stelle": the unit and route TEMPLATES
# live here and nowhere else, and the checks a first-time setup owes (name grammar, reserved names, a
# foreign systemd unit, a unit that would not run as its own service account) live here too — so
# devlab-install and devlab-deploy-recv can never drift apart on what a valid setup is.
#
# The route template's CONTAINER lives here too: a route is a naked `handle` block, valid only inside a
# site block, so setup_edge_caddyfile_text — the edge shell that devlab-install-recv --provision builds
# a bare host's edge from — sits beside setup_route_text. The container and its contents are one
# contract; keeping them in one file is what stops --provision from erecting an edge the delivered
# routes cannot live in.
#
# This file carries NO instance-specific value: every path is derived from the repo name (/opt/<repo>,
# /var/lib/<repo>) exactly as the wrappers that source it do. It must be root-owned and world-readable
# (mode 0755/0644), like the wrappers, so the unprivileged runner can source it during the build.

# Reserved identities, and the RULE they follow — copied verbatim from the namespace that devlab-install
# has always enforced, now SHARED so devlab-deploy-recv applies the identical list on the production
# host. Reserved is an identity that belongs to the operating system, to a third-party package, or to
# the landscape as a whole — one that can appear on a host without anybody's decision and that a setup
# must therefore never create, borrow or shadow. `root` is the sharpest case, because the unit template
# carries `User=<repo>`. A name the ORGANISATION can legitimately give a service of its own is NOT on
# this list even where a like-named OS account exists (a landscape may run a service called `mail`);
# what decides there are the identity checks below (foreign unit, foreign account), not the spelling.
SETUP_RESERVED_REPOS="root daemon bin sys nobody nogroup www-data adm
halt shutdown reboot init systemd udev dbus messagebus polkitd syslog rsyslog
sshd ssh cron atd chrony ntp named dnsmasq exim postfix dovecot sudo
caddy nginx apache apache2 httpd postgres postgresql mysql mariadb redis mongod
docker containerd kubelet etcd snapd holistic"

# setup_valid_repo_name <repo> — the SHAPE and NAMESPACE gate a name must pass before it reaches any
# path: the grammar ^[a-z][a-z0-9-]{2,30}$, no doubled or trailing dash, not systemd's own prefix, and
# not a reserved identity. Returns 0 when the name is admissible; otherwise it prints the reason to
# stderr and returns 1. The caller turns that into its own die/exit with its own exit code, so both
# wrappers keep their established exit-code contract while sharing the one rule-set.
setup_valid_repo_name() {
  local repo="$1" r
  [[ "$repo" =~ ^[a-z][a-z0-9-]{2,30}$ ]] || { echo "invalid repo name '$repo' (want ^[a-z][a-z0-9-]{2,30}\$)" >&2; return 1; }
  case "$repo" in
    *--* | *-) echo "invalid repo name '$repo' (no doubled and no trailing dash)" >&2; return 1 ;;
    systemd-*) echo "repo name '$repo' lies in systemd's own namespace" >&2; return 1 ;;
  esac
  for r in $SETUP_RESERVED_REPOS; do
    if [ "$repo" = "$r" ]; then
      echo "repo name '$repo' is reserved (operating-system, package or landscape identity) — a unit and a service account under this name would collide with an existing one" >&2
      return 1
    fi
  done
  return 0
}

# setup_unit_text <repo> <port> — THE systemd unit template. Every value is derived from the two
# validated arguments; the unit runs as User=<repo> (never root), confined by NoNewPrivileges/
# ProtectSystem to its own /var/lib/<repo>. This is the only place this text exists.
setup_unit_text() {
  local repo="$1" port="$2"
  cat <<UNIT
[Unit]
Description=${repo} — a holistic service (generated by devlab-install)
After=network.target

[Service]
User=${repo}
Environment=HOLISTIC_SECRET_FILE=/etc/holistic/jwt-secret
ExecStart=/opt/${repo}/bin/${repo}d --listen 127.0.0.1:${port}
Restart=on-failure
RestartSec=2
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/var/lib/${repo}
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNIT
}

# setup_route_text <repo> <port> — THE edge route template. Maps the service's API prefix to its
# loopback port; unit and route always carry the same port because they come from the same call.
# It is a NAKED `handle` block — a Caddy directive with no surrounding site block — because it is
# dropped into the shared route directory and IMPORTED into the edge's site block (see
# setup_edge_caddyfile_text). A naked directive is valid ONLY inside a site block; that is the
# contract these two templates share, and why they live together.
setup_route_text() {
  local repo="$1" port="$2"
  cat <<ROUTE
# Generated by devlab-install. Routes the service API to the daemon.
handle /api/services/${repo}/* {
	reverse_proxy 127.0.0.1:${port}
}
ROUTE
}

# setup_edge_caddyfile_text <conf_dir> <www_dir> [<site>] — THE host edge shell: the ONE site block
# the per-service routes REQUIRE. Every route from setup_route_text is a naked `handle` block that is
# valid only inside a site block, so the shell imports the whole route directory INSIDE one and adds a
# static fallback for the dashboard. This is the SAME shape a grown holistic host carries (a site block
# whose body imports conf.d and ends in a file_server), reduced to its instance-neutral core: no
# hostname (the site is a bare port so no domain is baked in — Keine Instanz-Spezifika), the conf.d and
# web paths supplied by the caller. It lives HERE, beside the route template, so the container and the
# thing it must contain can never drift into two incompatible descriptions of the same edge.
setup_edge_caddyfile_text() {
  local conf_dir="$1" www_dir="$2" site="${3:-:80}"
  cat <<EDGE
# Managed by devlab-install-recv — the Holistic edge shell. The per-service routes the receiver drops
# into ${conf_dir} are naked \`handle\` blocks; a naked directive is valid ONLY inside a site block, so
# they are imported INSIDE one here. Never add a bare directive or a second site block beside this one:
# Caddy refuses that as an ambiguous site definition and then NO delivered route validates. Regenerated
# on --provision; do not edit by hand.
${site} {
	import ${conf_dir}/*.caddy
	handle {
		root * ${www_dir}
		file_server
	}
}
EDGE
}

# setup_ensure_account <repo> — the service's own identity: a nologin SYSTEM account whose home is
# /var/lib/<repo>, created only when absent (idempotent). This is what `User=<repo>` in the unit runs
# as; devlab-install and devlab-deploy-recv create it identically at first-time setup.
setup_ensure_account() {
  local repo="$1"
  getent passwd "$repo" >/dev/null 2>&1 \
    || useradd --system --shell /usr/sbin/nologin --home-dir "/var/lib/$repo" "$repo"
  install -d -o "$repo" -g "$repo" -m 0755 "/var/lib/$repo"
}

# setup_fragment_path <repo> [<systemctl>] — echoes the FragmentPath systemd already knows for
# <repo>.service (whitespace-trimmed), empty when systemd knows no unit. The QUESTION is asked of
# systemd, not of a directory, so a vendor unit under /lib or /usr/lib — which a path test in
# /etc/systemd/system would not see — is visible and can be refused instead of silently shadowed.
setup_fragment_path() {
  local repo="$1" systemctl="${2:-systemctl}"
  "$systemctl" show -p FragmentPath --value "${repo}.service" 2>/dev/null | tr -d '[:space:]'
}

# setup_unit_declares_user <unit-file> <repo> — a DELIVERED unit is trusted only if it runs as its
# own service account: it must carry exactly `User=<repo>`. A unit that starts something else, or runs
# as root, or omits User= altogether, fails this and is refused (returns non-zero). devlab-install
# never needs this — it AUTHORS the line — but the production receiver, which INSTALLS a unit built
# elsewhere, must verify it before trusting it.
setup_unit_declares_user() {
  local file="$1" repo="$2"
  grep -Eq "^[[:space:]]*User[[:space:]]*=[[:space:]]*${repo}[[:space:]]*$" -- "$file"
}

# setup_unit_state <unit-name> <unit-dir> [<systemctl>] — the ONE first-time-vs-update-vs-foreign
# judgement, asked of SYSTEMD (setup_fragment_path), not of a directory, so a vendor unit under /lib
# or /usr/lib is seen and can be refused instead of silently shadowed. It echoes exactly one word so
# every consumer branches the same way instead of copying the case:
#   first           no unit anywhere — a first-time setup.
#   update          OUR unit (its fragment is <unit-dir>/<unit-name>.service, or systemd names none
#                   but the unit file is already present) — replace the program and restart.
#   foreign:<path>  a fragment OUTSIDE <unit-dir> holds the name — the caller refuses (it neither
#                   shadows nor overwrites a unit that is not its own).
# Always returns 0; the caller maps the word to its own die/exit code, so the receiver's generic
# service branch and its self-repo branch keep their established exit codes while sharing the one
# rule. The unit NAME is a parameter because the self repo's daemon (devlabd) is not named after its
# repository (devlab) — the judgement must not assume unit-name == repo-name.
setup_unit_state() {
  local unit="$1" unit_dir="$2" systemctl="${3:-systemctl}"
  local unit_file="$unit_dir/${unit}.service" frag
  frag="$(setup_fragment_path "$unit" "$systemctl")"
  case "$frag" in
    "$unit_file") echo update ;;
    "")           if [ -e "$unit_file" ]; then echo update; else echo first; fi ;;
    *)            echo "foreign:$frag" ;;
  esac
}

# setup_install_rights <rights-file> <perms-dir> <name> — install a DELIVERED rights manifest (a
# validated file COPY, never executed) into <perms-dir>/<name>.json and ensure the hp_* system groups
# it declares exist. The manifest layout and its grouping are identical for every service, so the
# receiver's generic branch and its self-repo branch install rights through this ONE function rather
# than each carrying its own copy of the grep+groupadd.
setup_install_rights() {
  local rights="$1" perms_dir="$2" name="$3" g
  install -d -m 0755 "$perms_dir"
  install -m 0644 "$rights" "$perms_dir/$name.json"
  grep -oE '"group"[[:space:]]*:[[:space:]]*"hp_[a-z0-9_]+"' "$rights" | grep -oE 'hp_[a-z0-9_]+' | sort -u |
    while read -r g; do groupadd -f "$g"; done
}

# setup_install_route <route-file> <route-dest> <conf-dir> <caddy-bin> <caddy-main> <systemctl> [unwind ...]
# Install a DELIVERED edge route into the SHARED route directory and prove the ASSEMBLED edge still
# validates before reloading it. The route directory is shared by every service of the host, so an
# unparseable file of ours would break the whole edge at the next reload: the route is validated IN
# PLACE and taken back out — together with every <unwind> file the caller names (e.g. the unit it just
# wrote) — on any failure, so the edge keeps its last good configuration. The reason is printed to
# stderr; the exit code lets the caller keep its own contract:
#   0  installed and the edge reloaded.
#   2  no route directory on this host — nothing installed (a delivered route is optional; the caller
#      decides whether that is fatal, and never creates the shared edge itself).
#   4  the assembled edge did not validate with the route, or caddy did not reload — an external-tool
#      failure; the route and the unwind files were removed.
#   5  the shared edge cannot be validated at all (no caddy / no main Caddyfile) — a config-state
#      failure; refusing to write into a directory serving every other service. Route removed.
setup_install_route() {
  local route="$1" dest="$2" conf_dir="$3" caddy_bin="$4" caddy_main="$5" systemctl="$6"; shift 6
  local unwind=("$@") out
  [ -d "$conf_dir" ] || return 2
  install -o root -g root -m 0644 "$route" "$dest"
  if command -v "$caddy_bin" >/dev/null 2>&1 && [ -f "$caddy_main" ]; then
    if ! out="$("$caddy_bin" validate --config "$caddy_main" 2>&1)"; then
      rm -f "$dest" "${unwind[@]}"
      echo "the edge configuration does not validate with the delivered route — route and unit removed, edge untouched: $(printf '%s' "$out" | tail -n 3)" >&2
      return 4
    fi
  else
    rm -f "$dest" "${unwind[@]}"
    echo "cannot validate the shared edge configuration ($caddy_bin / $caddy_main) — refusing to write into a config directory serving every other service" >&2
    return 5
  fi
  "$systemctl" reload caddy || { rm -f "$dest" "${unwind[@]}"; echo "caddy reload failed — route and unit removed so the edge keeps its last good configuration" >&2; return 4; }
  return 0
}
