#!/usr/bin/env bash
# Assemble deploy/MIGRATION.md from deploy/migration/*.md in the binding order.
#
# Why this exists: MIGRATION.md is the document the README names as the binding cutover, and it is a
# CONCATENATION of its parts. A hand-maintained concatenation drifts — an audit found the assembled copy
# still carrying an instance path that had already been replaced in the part it came from. So the
# assembly is a program, and `--check` fails when the tracked copy disagrees with its parts, which makes
# the drift a test failure instead of a surprise during the cutover.
#
# Usage:  tools/assemble-migration.sh            write deploy/MIGRATION.md
#         tools/assemble-migration.sh --check     exit 1 if the tracked copy is stale
set -euo pipefail
cd "$(dirname "$0")/.."

PARTS=(00-cutover 10-daten 20-sichtpruefung 80-vertragsaenderungen 90-geloescht)
OUT=deploy/MIGRATION.md

render() {
  cat <<'HEAD'
# MIGRATION — the DevLab rebuild's cutover

_Generated by `tools/assemble-migration.sh` from `deploy/migration/*.md` in the binding order
00 → 10 → 20 → 80 → 90 (BAUPLAN §4). Do not edit this file: edit the part it came from and run the
assembler. `tools/assemble-migration.sh --check` fails when this copy is stale._

The cutover is performed by the orchestrator as root, in the order of the sections below: the command
sequence (00), the one-off data items (10), the acceptance status per line plus the visual and measured
inspection of what neither a grep nor a test can decide (20), the log of every change to a frozen
contract (80), and what the scaffold deleted with its named replacement (90).
HEAD
  for p in "${PARTS[@]}"; do
    local f="deploy/migration/$p.md"
    [[ -f "$f" ]] || { echo "assemble-migration: missing part $f" >&2; exit 1; }
    printf '\n\n---\n\n<!-- from %s -->\n\n' "$f"
    cat "$f"
  done
}

if [[ "${1:-}" == "--check" ]]; then
  if diff -q <(render) "$OUT" >/dev/null 2>&1; then
    echo "MIGRATION.md is current"
  else
    echo "MIGRATION.md is STALE — run tools/assemble-migration.sh" >&2
    diff <(render) "$OUT" | head -40 >&2 || true
    exit 1
  fi
else
  render > "$OUT"
  echo "wrote $OUT ($(wc -l < "$OUT") lines from ${#PARTS[@]} parts)"
fi
