// CLAUDE.md constitution block (S5). The constitution reaches every implementation THROUGH THE
// PROMPT (the run's snapshot carries the full wording); the repo's CLAUDE.md carries only the
// short reference text below between two markers. Replacement touches ONLY the span between
// the markers — everything outside stays untouched. There is NO rollout: the replacement rides
// along as part of implement/publish of the one chain (B3 calls ReplaceConstitutionBlock; the
// rendering lives here).
package mercury

import "strings"

// Markers delimiting the managed constitution block inside a repo's CLAUDE.md (distilled from
// the retired rollout renderer).
const (
	ClaudeMDMarkerBegin = "<!-- holistic:constitution:begin -->"
	ClaudeMDMarkerEnd   = "<!-- holistic:constitution:end -->"
)

// The retired rollout wrote the FULL rendered constitution between these markers; every
// repository provisioned before the rebuild still carries them. ReplaceConstitutionBlock
// recognises them so the one-time swap to the reference text finds the legacy block, replaces
// it wholesale and leaves the canonical markers behind.
const (
	legacyMarkerBegin = "<!-- BEGIN HOLISTIC AXIOMS — generated by Mercury, do not edit -->"
	legacyMarkerEnd   = "<!-- END HOLISTIC AXIOMS -->"
)

// ReferenceText is the released CLAUDE.md reference text — the VERBATIM wording from the
// constitution source (deliberately German, as released; the constitution store carries the
// bilingual corpus). It names no address on purpose: an address would be an instance specific,
// which lives only in the runtime configuration. The text itself carries the one rule that
// sends a constitution-unaware session onto the regular path.
const ReferenceText = "# Holistic — Verfassung\n" +
	"\n" +
	"Für dieses Repository gelten die Holistic-Axiome und Implementierungsregeln.\n" +
	"Ihr verbindlicher Wortlaut wird nicht hier geführt, sondern mit jedem\n" +
	"Implementierungsauftrag mitgeliefert. So gilt immer der aktuelle Stand.\n" +
	"\n" +
	"**Arbeitest du im Auftrag von Mercury:** Der Wortlaut steht vollständig in\n" +
	"deinem Prompt. Er hat Vorrang vor jeder anderen Fassung, die dir begegnet.\n" +
	"\n" +
	"**Arbeitest du in einer von Hand geöffneten Sitzung:** Implementiere nicht\n" +
	"selbst. Lege die Arbeit als ToDo in Mercury an und führe es aus — dann kommt\n" +
	"der verbindliche Wortlaut auf dem regulären Weg. Der Verfassungs-Bestand wird\n" +
	"in der Laufzeit-Konfiguration der Instanz benannt.\n"

// referenceRegion is the canonical managed block: the reference text between the markers.
func referenceRegion() string {
	return ClaudeMDMarkerBegin + "\n" + strings.TrimRight(ReferenceText, "\n") + "\n" + ClaudeMDMarkerEnd
}

// ReplaceConstitutionBlock replaces the span between the markers in doc with the reference
// text, leaving everything outside untouched. Both the canonical markers and the retired
// rollout's legacy markers are recognised (the legacy pair is swapped for the canonical one).
// A document without markers gets the block appended (markers included). Returns the new
// document and whether it changed. Idempotent: applying it to its own output changes nothing.
func ReplaceConstitutionBlock(doc string) (string, bool) {
	region := referenceRegion()

	out, ok := splice(doc, ClaudeMDMarkerBegin, ClaudeMDMarkerEnd, region)
	if !ok {
		out, ok = splice(doc, legacyMarkerBegin, legacyMarkerEnd, region)
	}
	if !ok {
		// No managed block yet: append it, after a blank line when the document has content.
		if strings.TrimSpace(doc) == "" {
			out = region + "\n"
		} else {
			out = strings.TrimRight(doc, "\n") + "\n\n" + region + "\n"
		}
	}
	return out, out != doc
}

// splice replaces the span from `begin` through `end` (markers included) with region, keeping
// every byte outside the span. A begin without an end swallows the tail (the block IS the
// tail then — appending instead would duplicate it). Returns ok=false when begin is absent.
func splice(doc, begin, end, region string) (string, bool) {
	b := strings.Index(doc, begin)
	if b < 0 {
		return "", false
	}
	rest := doc[b:]
	if e := strings.Index(rest, end); e >= 0 {
		return doc[:b] + region + rest[e+len(end):], true
	}
	return doc[:b] + region + "\n", true
}
