package mercury

import (
	"strings"
	"testing"
)

// The marker replacement swaps ONLY the span between the markers; every byte before and after
// survives verbatim (REQ-002.2/5 — the repo's CLAUDE.md carries the reference text, the rest of
// the file is the repo's own).
func TestReplaceConstitutionBlockKeepsOutsideUntouched(t *testing.T) {
	prefix := "# My service\n\nHand-written notes that must survive.\n\n"
	suffix := "\n\n## Local conventions\n\nMore hand-written content.\n"
	doc := prefix + ClaudeMDMarkerBegin + "\nOLD RENDERED CONSTITUTION\n" + ClaudeMDMarkerEnd + suffix

	out, changed := ReplaceConstitutionBlock(doc)
	if !changed {
		t.Fatal("a differing block must report changed")
	}
	if !strings.HasPrefix(out, prefix) {
		t.Errorf("prefix was not preserved byte-for-byte:\n%q", out)
	}
	if !strings.HasSuffix(out, suffix) {
		t.Errorf("suffix was not preserved byte-for-byte:\n%q", out)
	}
	if strings.Contains(out, "OLD RENDERED CONSTITUTION") {
		t.Error("the old block must be fully replaced")
	}
	if !strings.Contains(out, strings.TrimRight(ReferenceText, "\n")) {
		t.Error("the reference text must sit between the markers")
	}
	if strings.Count(out, ClaudeMDMarkerBegin) != 1 || strings.Count(out, ClaudeMDMarkerEnd) != 1 {
		t.Error("exactly one marker pair must remain")
	}
}

// Repositories provisioned by the retired rollout carry the legacy marker pair around a fully
// rendered constitution. The one-time swap must find that block, replace it wholesale with the
// reference text and leave the canonical markers — everything outside stays.
func TestReplaceConstitutionBlockMigratesLegacyMarkers(t *testing.T) {
	legacyBegin := "<!-- BEGIN HOLISTIC AXIOMS — generated by Mercury, do not edit -->"
	legacyEnd := "<!-- END HOLISTIC AXIOMS -->"
	doc := legacyBegin + "\n# Holistic — Axiome & Implementierungsregeln\n\n## Axiome\n\n- lots of rendered wording\n" +
		legacyEnd + "\n\n# Repo notes\n\nkept.\n"

	out, changed := ReplaceConstitutionBlock(doc)
	if !changed {
		t.Fatal("the legacy block must be replaced")
	}
	if strings.Contains(out, legacyBegin) || strings.Contains(out, legacyEnd) {
		t.Error("legacy markers must be swapped for the canonical pair")
	}
	if !strings.Contains(out, ClaudeMDMarkerBegin) || !strings.Contains(out, ClaudeMDMarkerEnd) {
		t.Error("the canonical markers must delimit the new block")
	}
	if strings.Contains(out, "lots of rendered wording") {
		t.Error("the rendered constitution must be gone — the prompt carries the wording now")
	}
	if !strings.HasSuffix(out, "\n\n# Repo notes\n\nkept.\n") {
		t.Errorf("content after the legacy block must survive:\n%q", out)
	}
}

// A CLAUDE.md without any managed block gets the block appended (markers included); an empty
// document becomes just the block.
func TestReplaceConstitutionBlockAppendsWhenAbsent(t *testing.T) {
	out, changed := ReplaceConstitutionBlock("# Notes\n")
	if !changed || !strings.HasPrefix(out, "# Notes\n\n"+ClaudeMDMarkerBegin) {
		t.Errorf("block must be appended after the existing content:\n%q", out)
	}
	if !strings.HasSuffix(out, ClaudeMDMarkerEnd+"\n") {
		t.Errorf("appended block must close with the end marker:\n%q", out)
	}

	out, changed = ReplaceConstitutionBlock("")
	if !changed || !strings.HasPrefix(out, ClaudeMDMarkerBegin) {
		t.Errorf("an empty document becomes exactly the block:\n%q", out)
	}
}

// Applying the replacement to its own output changes nothing — the ride-along in every delivery
// (REQ-002.5) is a no-op once a repo carries the reference text.
func TestReplaceConstitutionBlockIdempotent(t *testing.T) {
	for _, start := range []string{
		"",
		"# Notes\n",
		"pre\n" + ClaudeMDMarkerBegin + "\nstale\n" + ClaudeMDMarkerEnd + "\npost\n",
	} {
		once, _ := ReplaceConstitutionBlock(start)
		twice, changed := ReplaceConstitutionBlock(once)
		if changed || twice != once {
			t.Errorf("second application must be a no-op (start=%q)", start)
		}
	}
}

// A begin marker whose end marker was lost swallows the tail instead of appending a second
// block — the managed block is the tail then, never duplicated.
func TestReplaceConstitutionBlockHandlesMissingEndMarker(t *testing.T) {
	doc := "keep\n" + ClaudeMDMarkerBegin + "\ntruncated remainder without end"
	out, changed := ReplaceConstitutionBlock(doc)
	if !changed {
		t.Fatal("a truncated block must be repaired")
	}
	if strings.Count(out, ClaudeMDMarkerBegin) != 1 || strings.Count(out, ClaudeMDMarkerEnd) != 1 {
		t.Errorf("repair must leave exactly one complete marker pair:\n%q", out)
	}
	if !strings.HasPrefix(out, "keep\n") || strings.Contains(out, "truncated remainder") {
		t.Errorf("content before the marker stays, the truncated tail goes:\n%q", out)
	}
}

// The reference text is the released wording (D §3): it routes a Mercury-tasked session to its
// prompt and a hand-opened session to the ToDo path, and it names NO address — an address would
// be an instance specific, which lives only in the runtime configuration.
func TestReferenceTextIsTheReleasedWording(t *testing.T) {
	for _, want := range []string{
		"# Holistic — Verfassung",
		"Für dieses Repository gelten die Holistic-Axiome und Implementierungsregeln.",
		"**Arbeitest du im Auftrag von Mercury:** Der Wortlaut steht vollständig in\ndeinem Prompt.",
		"**Arbeitest du in einer von Hand geöffneten Sitzung:** Implementiere nicht\nselbst.",
		"Der Verfassungs-Bestand wird\nin der Laufzeit-Konfiguration der Instanz benannt.",
	} {
		if !strings.Contains(ReferenceText, want) {
			t.Errorf("reference text is missing the released passage %q", want)
		}
	}
	for _, forbidden := range []string{"http://", "https://", "github.com", "/home/", "/var/"} {
		if strings.Contains(ReferenceText, forbidden) {
			t.Errorf("reference text must name no address or path, found %q", forbidden)
		}
	}
	if strings.Contains(ReferenceText, "TODO") {
		t.Error("placeholder text survived into the released wording")
	}
}
