package mercury

import (
	"fmt"
	"sort"
	"strings"
)

// The rollout writes the axioms + implementation rules into every holistic repo's CLAUDE.md, so
// Claude Code sees them wherever it works. Only the region between the markers is generated; the
// rest of each repo's CLAUDE.md is preserved byte-for-byte — the same splice discipline the axiom
// document itself uses.

const (
	MarkerBegin = "<!-- BEGIN HOLISTIC AXIOMS — generated by Mercury, do not edit -->"
	MarkerEnd   = "<!-- END HOLISTIC AXIOMS -->"
)

// Record is one stored axiom or rule: its path and parsed content.
type Record struct {
	Path  string
	Axiom Axiom
}

// SpliceMarker replaces the generated region of old with block, preserving everything outside the
// markers. When old has no markers, block is appended (after a blank line if old is non-empty). The
// result always ends with a single trailing newline.
func SpliceMarker(old, block string) string {
	region := MarkerBegin + "\n" + block + "\n" + MarkerEnd

	begin := strings.Index(old, MarkerBegin)
	end := strings.Index(old, MarkerEnd)
	var out string
	if begin >= 0 && end > begin {
		out = old[:begin] + region + old[end+len(MarkerEnd):]
	} else if strings.TrimSpace(old) == "" {
		out = region
	} else {
		out = strings.TrimRight(old, "\n") + "\n\n" + region
	}
	return strings.TrimRight(out, "\n") + "\n"
}

// RenderBlock renders the axioms and rules as the markdown that goes between the markers: a heading
// per top-level namespace, categories as nested headings, each axiom as a titled bullet. Records are
// grouped by their path so the output is deterministic and diffable.
func RenderBlock(axiome, regeln []Record) string {
	var b strings.Builder
	b.WriteString("# Holistic — Axiome & Implementierungsregeln\n\n")
	b.WriteString("_Automatisch aus Mercury ausgerollt. Nicht direkt bearbeiten; ändere die Axiome in DevLab → Mercury._\n")

	if len(axiome) > 0 {
		b.WriteString("\n## Axiome\n")
		renderRecords(&b, NsAxiome, axiome)
	}
	if len(regeln) > 0 {
		b.WriteString("\n## Implementierungsregeln\n")
		renderRecords(&b, NsRegeln, regeln)
	}
	return strings.TrimRight(b.String(), "\n")
}

// renderRecords writes records grouped by their category path, emitting a category subheading when
// it changes and each axiom as a "- **Titel** — body" bullet.
func renderRecords(b *strings.Builder, ns string, records []Record) {
	sorted := append([]Record(nil), records...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Path < sorted[j].Path })

	lastCat := ""
	for _, r := range sorted {
		cat := category(r.Path, ns)
		if cat != lastCat {
			b.WriteString("\n### " + cat + "\n")
			lastCat = cat
		}
		title := r.Axiom.Titel
		if title == "" {
			title = leafName(r.Path)
		}
		body := strings.ReplaceAll(strings.TrimSpace(r.Axiom.Body), "\n", " ")
		fmt.Fprintf(b, "- **%s** — %s\n", title, body)
	}
}

// category is the human path of a record's parent category (namespace stripped, slashes → " / ").
func category(path, ns string) string {
	p := strings.TrimSuffix(strings.TrimPrefix(path, ns+"/"), ".md")
	segs := strings.Split(p, "/")
	if len(segs) <= 1 {
		return "(allgemein)"
	}
	return strings.Join(segs[:len(segs)-1], " / ")
}

func leafName(path string) string {
	base := path[strings.LastIndex(path, "/")+1:]
	return strings.TrimSuffix(base, ".md")
}
